spring.application.name=payment

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payments
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Encryption key (32 bytes for AES-256)
encryption.key=n8f9k2m5L7jR3wQ6bN1vX4yP9sH8dF2a
